TARGET = libpedsim.so
SOURCES = $(shell echo *.cpp)
OBJECTS = $(SOURCES:.cpp=.o)
LDFLAGS = -shared
CXXFLAGS = -fPIC -msse4.1 -mavx  -fopenmp -DNOCUDA --std=c++14 -g
INCPATH=
LDFLAGS+= 
LDFLAGS+= -lgomp -shared

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CXX) $(FLAGS) $(CXXFLAGS) $(DEBUGFLAGS) $(LDFLAGS) -o $(TARGET) $(OBJECTS)

%.o: %.cpp
	$(CXX) $(FLAGS) $(CXXFLAGS) $(INCPATH) -c -o $@ $<



clean:
	-rm $(TARGET) $(OBJECTS)
